apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
  namespace: default
  labels:
    app: nodejs-app
    version: green
spec:
  replicas: 0  # Initially scaled to 0
  selector:
    matchLabels:
      app: nodejs-app
      version: green
  template:
    metadata:
      labels:
        app: nodejs-app
        version: green
    spec:
      containers:
      - name: nodejs-app
        image: 603480426027.dkr.ecr.us-west-2.amazonaws.com/nodejs-app:green
        ports:
        - containerPort: 3000
        env:
        - name: VERSION
          value: "green"
        - name: BUILD_NUMBER
          value: "2"
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
