apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/blue-green-deploy: "true"
    # For canary testing (optional):
    # nginx.ingress.kubernetes.io/canary: "true"
    # nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: "aaa72dc9d10da4d1cbc664ee91114d82-715267764.us-west-2.elb.amazonaws.com"  # Replace with your real domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-app-blue  # Default to blue
            port:
              number: 80
